export default {
  GET_MOVIES: "GET_MOVIES",
  GET_CATEGORIES: "GET_CATEGORIES",
  FILTER_MOVIES: "FILTER_MOVIES",
  LIKE_MOVIE: "LIKE_MOVIE",
  DISLIKE_MOVIE: "DISLIKE_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE"
};
